permalink: /:year/:month/:day/:title
auto: false
pygments: true
paginate: 10
exclude: ['public', 'bin', 'vendor', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'unicorn.rb', 'config.ru', 'README.md']
destination: 'public'

production_url: http://www.matthewheston.com
title : matthewheston [dot] com
author:
  name: Matthew Heston
  email: mh@matthewheston.com
